### PR TITLE
Create DelayedBoolean.java

### LINKED ISSUE #8: Add Delayed Boolean to our Util Library
Base off - https://github.com/frc1678/C2023-Public/blob/3918db0720bc2d89c649dad6a2ea24ec801ef549/src/main/java/com/team1678/lib/util/DelayedBoolean.java#L6

### PR DESCRIPTION
**Pull request by Daniel-J101**
also added an equivalent delay method to triggers

### CODE REVIEW

**Comment by allengregoryiv** [comment]
@Daniel-J101 how does the trigger work as a static method? If you have two of them what happens?

**Comment by Daniel-J101** [comment]
image
image
I'm not sure what you mean, it's supposed to be a static method to add a delay to any trigger we use by creating a new trigger that just has additional logic. 
As far as I know having two method calls shouldn't cause any issues

**Comment by Daniel-J101** [comment]
Also I just noticed that the motors in mechanisms are no longer protected. Is it supposed to be public?

**Comment by SpectrumFRC3847** [comment]
I don't think so, they can be protected.

But back in topic, doesn't Delayed Trigger use the same static state for
both triggers if they are called at the same time?

**Comment by allengregoryiv** [comment]
Okay I think I understand what you did, sorry I was reading on my phone, you are good this should work.

**Pull request merged**
